### ISSUE TITLE
Biocache-service download issues (placeholder)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#432]
- [ ] #58 Improve downloads multimedia implementation
- [ ] #430 Downloads not setting a source value for 'ALA' when sending to logger
- [ ] #390 IndexOutOfBoundsException in SpeciesLookupRestService
- [ ] #524 Download fails with IndexOutOfBoundsException

**Comment by adam-collins** [comment]
linked issues are closed
